@base = http://localhost:4000
@application-json = Content-Type: application/json
@email = test@email.com
@password = test-user-1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoidXNlciIsIl9pZCI6IjVlNjE4OTIwNDFhMzc3NjJhZTg2ZWIwYSIsImZpcnN0TmFtZSI6IlJ5YW4iLCJsYXN0TmFtZSI6IkdvbnphbGVzIiwiZGlzcGxheU5hbWUiOiJyZ29uemFsZXMiLCJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMC0wMy0wNVQyMzoyMDowMC40NjdaIiwidXBkYXRlZEF0IjoiMjAyMC0wMy0wNVQyMzoyMDowMC40NjdaIiwiX192IjowfSwiaWF0IjoxNTg0MTYwODQ3LCJleHAiOjE1ODQyNDcyNDd9.cISh8zRSV5q5DDfrDn92VeAH9_AnMSuyZV2LBqca8s0

### Register user
POST {{base}}/auth/register
{{application-json}}

{
  "firstName": "Ryan",
  "lastName": "Gonzales",
  "displayName": "rgonzales",
  "email": "{{email}}",
  "password": "{{password}}"
}

### Validate user
POST {{base}}/auth/validate
{{application-json}}

{
  "token": "{{token}}"
}

### Login
POST {{base}}/auth/login
{{application-json}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}