@base = http://localhost:4000
@application-json = Content-Type: application/json
@email = test@email.com
@password = test-user-1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJfaWQiOiI1ZTYxODkyMDQxYTM3NzYyYWU4NmViMGEiLCJmaXJzdE5hbWUiOiJSeWFuIiwibGFzdE5hbWUiOiJHb256YWxlcyIsImRpc3BsYXlOYW1lIjoicmdvbnphbGVzIiwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjAtMDMtMDVUMjM6MjA6MDAuNDY3WiIsInVwZGF0ZWRBdCI6IjIwMjAtMDMtMDVUMjM6MjA6MDAuNDY3WiIsIl9fdiI6MH0sImlhdCI6MTU4MzcwODExNCwiZXhwIjoxNTgzNzk0NTE0fQ.GReG3Abd2Qu2pELn002RwI47Dgo6BSDS7ej_jcqaM6Y

### Register user
POST {{base}}/auth/register
{{application-json}}

{
  "firstName": "Ryan",
  "lastName": "Gonzales",
  "displayName": "rgonzales",
  "email": "{{email}}",
  "password": "{{password}}"
}

### Validate user
POST {{base}}/auth/validate
{{application-json}}

{
  "token": "{{token}}"
}

### Login
POST {{base}}/auth/login
{{application-json}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}