@base = http://localhost:4000
@application-json = Content-Type: application/json
@email = test@email.com
@password = test-user-1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoidXNlciIsIl9pZCI6IjVlNjE4OTIwNDFhMzc3NjJhZTg2ZWIwYSIsImZpcnN0TmFtZSI6IlJ5YW4iLCJsYXN0TmFtZSI6IkdvbnphbGVzIiwiZGlzcGxheU5hbWUiOiJyZ29uemFsZXMiLCJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMC0wMy0wNVQyMzoyMDowMC40NjdaIiwidXBkYXRlZEF0IjoiMjAyMC0wMy0wNVQyMzoyMDowMC40NjdaIiwiX192IjowfSwiaWF0IjoxNTg4NDQzMDU5LCJleHAiOjE1ODg1Mjk0NTl9.-CY8T1tW_BdFY6jTnX1MuNq0SiaYxk5tSNaofi9HI9Q

### Register user
POST {{base}}/auth/register
{{application-json}}

{
  "firstName": "Ryan",
  "lastName": "Gonzales",
  "displayName": "rgonzales",
  "email": "{{email}}",
  "password": "{{password}}"
}

### Validate user
POST {{base}}/auth/validate
{{application-json}}

{
  "token": "{{token}}"
}

### Login
POST {{base}}/auth/login
{{application-json}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}