@base = http://localhost:4000
@application-json = Content-Type: application/json
@id = 5eae2f83527cbc603cc0cd4d
@userId = 5e61892041a37762ae86eb0a
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoidXNlciIsIl9pZCI6IjVlNjE4OTIwNDFhMzc3NjJhZTg2ZWIwYSIsImZpcnN0TmFtZSI6IlJ5YW4iLCJsYXN0TmFtZSI6IkdvbnphbGVzIiwiZGlzcGxheU5hbWUiOiJyZ29uemFsZXMiLCJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMC0wMy0wNVQyMzoyMDowMC40NjdaIiwidXBkYXRlZEF0IjoiMjAyMC0wMy0wNVQyMzoyMDowMC40NjdaIiwiX192IjowfSwiaWF0IjoxNTg4NDc0MDYwLCJleHAiOjE1ODg1NjA0NjB9.ubXrtd0No2sc7nl28oYF3B2YKh-eJl-kbX8mJbIRoBI
@authorization = Authorization: {{token}}
@parentId = 5e65cadd8254cd65dd57fb7d

### Get all comments
GET {{base}}/comments/all
{{application-json}}
{{authorization}}

### Create a comment
POST {{base}}/comments
{{application-json}}
{{authorization}}

{
  "parentId": "{{parentId}}",
  "body": "This is the very first comment on this video",
  "user": "{{userId}}"
}

### Get a comment
GET {{base}}/comments/{{id}}
{{application-json}}
{{authorization}}

### Updates a comment
PUT {{base}}/comments/{{id}}
{{application-json}}
{{authorization}}

### Deletes a comment
DELETE {{base}}/comments/{{id}}
{{application-json}}
{{authorization}}

### Delete all comments
DELETE {{base}}/comments/all
{{application-json}}
{{authorization}}