@base = http://localhost:4000
@application-json = Content-Type: application/json
@id = 5e61892041a37762ae86eb0a
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJfaWQiOiI1ZTYxODkyMDQxYTM3NzYyYWU4NmViMGEiLCJmaXJzdE5hbWUiOiJSeWFuIiwibGFzdE5hbWUiOiJHb256YWxlcyIsImRpc3BsYXlOYW1lIjoicmdvbnphbGVzIiwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjAtMDMtMDVUMjM6MjA6MDAuNDY3WiIsInVwZGF0ZWRBdCI6IjIwMjAtMDMtMDVUMjM6MjA6MDAuNDY3WiIsIl9fdiI6MH0sImlhdCI6MTU4Mzc5NDU1OCwiZXhwIjoxNTgzODgwOTU4fQ.-cEf0ckaKBBYT7zLO_SFFj1TRLCl2ICoGbCrj1QIfqo
@authorization = Authorization: {{token}}

### Get all users
GET {{base}}/users/all
{{application-json}}
{{authorization}}

### Get user
GET {{base}}/users/{{id}}
{{application-json}}
{{authorization}}

### Delete user
DELETE {{base}}/users/{{id}}
{{application-json}}

# ### Get all user video lists
# GET {{base}}/users/{{id}}/