@base = http://localhost:4000
@application-json = Content-Type: application/json
@id = 5e6411e05d938c317b873924
@userId = 5e61892041a37762ae86eb0a
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJfaWQiOiI1ZTYxODkyMDQxYTM3NzYyYWU4NmViMGEiLCJmaXJzdE5hbWUiOiJSeWFuIiwibGFzdE5hbWUiOiJHb256YWxlcyIsImRpc3BsYXlOYW1lIjoicmdvbnphbGVzIiwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjAtMDMtMDVUMjM6MjA6MDAuNDY3WiIsInVwZGF0ZWRBdCI6IjIwMjAtMDMtMDVUMjM6MjA6MDAuNDY3WiIsIl9fdiI6MH0sImlhdCI6MTU4MzgyMDkxMiwiZXhwIjoxNTgzOTA3MzEyfQ.pWw8IFjII24NSavYggPaWcvgUzHn-VjeWqg28jz-qYw
@authorization = Authorization: {{token}}

### Get all videos in a videoList
GET {{base}}/videoLists/{{id}}/videos
{{application-json}}
{{authorization}}

### Get all user video lists
GET {{base}}/videoLists/{{userId}}/user
{{application-json}}
{{authorization}}

### Get all video lists
GET {{base}}/videoLists/all
{{application-json}}
{{authorization}}

### Create a video list
POST {{base}}/videoLists
{{application-json}}
{{authorization}}

{
  "name": "",
  "userId": "{{userId}}"
}

### Get a video list
GET {{base}}/videoLists/{{id}}
{{application-json}}
{{authorization}}


### Update a video list
PUT {{base}}/videoLists/{{id}}
{{application-json}}
{{authorization}}

{
  "name": "Third List"
}

### Delete a video list
DELETE {{base}}/videoLists/{{id}}
{{application-json}}
{{authorization}}