@base = http://localhost:4000
@application-json = Content-Type: application/json
@id = 5e6c60901467beb2cfb2be7d
@userId = 5e61892041a37762ae86eb0a
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoidXNlciIsIl9pZCI6IjVlNjE4OTIwNDFhMzc3NjJhZTg2ZWIwYSIsImZpcnN0TmFtZSI6IlJ5YW4iLCJsYXN0TmFtZSI6IkdvbnphbGVzIiwiZGlzcGxheU5hbWUiOiJyZ29uemFsZXMiLCJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMC0wMy0wNVQyMzoyMDowMC40NjdaIiwidXBkYXRlZEF0IjoiMjAyMC0wMy0wNVQyMzoyMDowMC40NjdaIiwiX192IjowfSwiaWF0IjoxNTg0MTYwODQ3LCJleHAiOjE1ODQyNDcyNDd9.cISh8zRSV5q5DDfrDn92VeAH9_AnMSuyZV2LBqca8s0
@authorization = Authorization: {{token}}
@videoListId = 5e6411e05d938c317b873924

### Get all videos
GET {{base}}/videos/all
{{application-json}}
{{authorization}}

### Create a video
POST {{base}}/videos
{{application-json}}
{{authorization}}

{
  "url": "https//ryangonz.com",
  "videoListId": "{{videoListId}}",
  "title": "Delete Me",
  "description": "This is the one to be deleted"
}

### Get a video
GET {{base}}/videos/{{id}}
{{application-json}}
{{authorization}}

### Update a video
PUT {{base}}/videos/{{id}}
{{application-json}}
{{authorization}}

{
  "url": "https://www.youtube.com/watch?v=RHqB8MZ0yK0",
  "views": 1,
  "title": "Tutorial with the spiders",
  "description": ""
}

### Delete a video
DELETE {{base}}/videos/{{id}}
{{application-json}}
{{authorization}}