@base = http://localhost:4000
@application-json = Content-Type: application/json
@id = 5eae2f74527cbc603cc0cd4c
@userId = 5e61892041a37762ae86eb0a
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ0eXBlIjoidXNlciIsIl9pZCI6IjVlNjE4OTIwNDFhMzc3NjJhZTg2ZWIwYSIsImZpcnN0TmFtZSI6IlJ5YW4iLCJsYXN0TmFtZSI6IkdvbnphbGVzIiwiZGlzcGxheU5hbWUiOiJyZ29uemFsZXMiLCJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMC0wMy0wNVQyMzoyMDowMC40NjdaIiwidXBkYXRlZEF0IjoiMjAyMC0wMy0wNVQyMzoyMDowMC40NjdaIiwiX192IjowfSwiaWF0IjoxNTg5NDI3Njc4LCJleHAiOjE1ODk1MTQwNzh9.YNKHS_gPsp1T4qBJbNRKUyvJGT1xtkGK41C8ozd7O3s
@authorization = Authorization: {{token}}
@videoListId = 5e6411e05d938c317b873924
@userId = 5e61892041a37762ae86eb0a

### Get all videos
GET {{base}}/videos/all
{{application-json}}
{{authorization}}

### Create a video
POST {{base}}/videos
{{application-json}}
{{authorization}}

{
  "url": "https://www.youtube.com/watch?v=RHqB8MZ0yK0",
  "videoListId": "{{videoListId}}",
  "title": "Newest video with user",
  "description": "This is the one with the user",
  "userId": "{{userId}}"
}

### Get a video
GET {{base}}/videos/{{id}}
{{application-json}}
{{authorization}}

### Update a video
PUT {{base}}/videos/{{id}}
{{application-json}}
{{authorization}}

{
  "url": "https://www.youtube.com/watch?v=RHqB8MZ0yK0",
  "views": 0,
  "title": "Tutorial with the spiders",
  "description": ""
}

### Delete a video
DELETE {{base}}/videos/{{id}}
{{application-json}}
{{authorization}}

### Gets video comments
GET {{base}}/videos/{{id}}/comments
{{application-json}}
{{authorization}}