@base = http://localhost:4000
@application-json = Content-Type: application/json
@id = 5e61892041a37762ae86eb0a
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNjE4OTIwNDFhMzc3NjJhZTg2ZWIwYSIsImlhdCI6MTU4MzQ1MDQwMCwiZXhwIjoxNTgzNTM2ODAwfQ.M2_W5avQ38bc_aKD6QMc023Xt4q5oYhum7DZYacDMTs
@authorization = Authorization: {{token}}

### Get all video lists
GET {{base}}/videoLists/all
{{application-json}}
{{authorization}}

### Create a video list
POST {{base}}/videoLists
{{application-json}}
{{authorization}}

{
  "name": "First List",
  "userId": "{{id}}"
}